server:
#   logLevel: debug
  logLevel: trace

globals:
  datasetBaseUrl: env:DATASET_BASE_URL
  endpoints:
    default:
      url: /query

plugins:
  static-assets:
    module: trifid-core/plugins/static.js
    order: 0
    paths: /static-assets
    config:
      directory: file:static

  welcome:
    module: trifid-core/plugins/view.js
    paths: /
    methods: GET
    config:
      path: /instances/gbad/welcome.hbs

  yasgui:
    module: trifid-plugin-yasgui
    paths:
      - /sparql
      - /sparql/
    config:
      #endpointUrl: https://example.com/query
      #urlShortener: https://example.com/api/v1/shorten
      defaultQuery: |
        PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>

        SELECT (COUNT(*) AS ?count)
        WHERE {
          ?s ?p ?o .
        } LIMIT 10
      # …other configuration fields

  graph-explorer:
    module: trifid-plugin-graph-explorer
    paths:
      - /graph-explorer
      - /graph-explorer/
    config:
      acceptBlankNodes: false
      #template: views/graph-explorer.hbs
      #dataLabelProperty: rdfs:label | <http://schema.org/name>
      #schemaLabelProperty: rdfs:label | <http://schema.org/name>
      language: en
      languages:
        - code: en
          label: English
        - code: de
          label: German
        - code: fr
          label: French
        - code: it
          label: Italian

  spex:
    module: trifid-plugin-spex
    paths:
      - /spex
      - /spex/
    config:
      prefixes:
        - prefix: add
          namespace: https://data.archives.gov.on.ca/Schema/Description-Listings/
        - prefix: auth
          namespace: https://data.archives.gov.on.ca/Schema/Authority/

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      path: /instances/gbad/render.hbs
      followRedirects: true
      labelLoader:
        chunkSize: 30
        concurrency: 2
        timeout: 4000

  fetch-handler:
    module: trifid-handler-fetch
    paths: /query
    config:
      url: env:FETCH_HANDLER_FILE
      contentType: env:FETCH_HANDLER_FILE_TYPE
      baseIRI: http://localhost:8080
      graphName: urn:x-rdflib:default
      unionDefaultGraph: true
      queryLogLevel: trace
